resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/cah-johnkeyes/concourse-demo-app.git
      branch: master

jobs:
  - name: unit-test
    plan:
      - get: source-code
        trigger: true
      - task: run-tests
        priviledged: true
        file: source-code/ci/tasks/unit-test.yml
  - name: publish
    plan:
      - get: source-code
        success: [unit-test]
      - task: publish
        priviledged: true
        file: source-code/ci/tasks/assemble-publish.yml